### ISSUE TITLE
load_latlngJSON documentation not listed on website

### ISSUE THREAD

**Issue by DeeptanshuM** [PurdueCAM2Project/CAM2WebUI#102]
[load_latlngJSON](https://github.com/PurdueCAM2Project/CAM2WebUI/blob/master/docs/implementationDetail/load_latlngJSON.md) is not listed on [documentation website](https://purduecam2project.github.io/CAM2WebUI/), it should be under 'implementation details' section

**Comment by huangyutong** [comment]
new files has to be added to docs/index.rst to be listed on sidebar of documentation site. beside, Travis didn't pass yesterday so no deployment occur. This happens randomly and should be Travis problem
