### ISSUE TITLE
failed re-captcha cleared the form for contact us and join us page

### ISSUE THREAD

**Issue by matthew-ardi** [PurdueCAM2Project/CAM2WebUI#270]
when someone fill out the form and forget to check off the re-captcha, the web refreshes the form and does not save the content of the form. This will force people to rewrite the form.

**Comment by nhendy** [comment]
@waynewhbaaa you implemented this correct? If so, please leave a permalink to your implementation and close this issue

**Comment by waynewhbaaa** [comment]
This issue has already been fixed at branch at 404. Please refer to my meeting report at page 5 [https://drive.google.com/drive/folders/1so_ctwymVesB9wwIY1leGwHQsS3HcRX7](url)
