### ISSUE TITLE
Need to update link on a documentation page

### ISSUE THREAD

**Issue by DeeptanshuM** [PurdueCAM2Project/CAM2WebUI#75]
Need to update link on page [Google Fusion Table Sync](https://github.com/PurdueCAM2Project/CAM2WebUI/blob/master/docs/implementationDetail/fusion.md)

- 'Upload Files to Google Drive' should be replaced with 'Introduction to Google Fusion Tables'
- The old link should be replaced with https://github.com/PurdueCAM2Project/CAM2WebUI/blob/master/docs/implementationDetail/fusion_setup.md

**Comment by huangyutong** [comment]
solved
